### PR TITLE
Created a Level and Template

### PR DESCRIPTION
**Pull request by Warladd**
Created a first level, created a template anyone can use, changed the timer to only be every 0.75 seconds so it wasn't super slow, created a more automatic system for the level select scene. Possible a bit more, not sure what else though.

### CODE REVIEW

**Comment by Warladd** [comment]
Don't approve and merge this until the pause menu is approved and merged

**Review by NexusKitten — COMMENTED** [review]
tastes legit

**Review by NexusKitten — APPROVED** [review]
wait i had to click approve

**Comment by Warladd** [comment]
Don't merge yet

**Comment by Warladd** [comment]
Approve the pause menu first

**Pull request merged**
